### ISSUE TITLE
[Bug]: Documentation issue

### ISSUE THREAD

**Issue by HeartlandTechie** [stephenjude/filament-feature-flags#12]
### What happened?

public function panel(Panel $panel): Panel
{
    return $panel
        ->plugin(
            Stephenjude\FilamentFeatureFlag\FeatureFlagPlugin::make()
        );
}

### How to reproduce the bug

The documentation just needs to be updated:

    \Stephenjude\FilamentFeatureFlag\FeatureFlagPlugin::make()

### Package Version

current

### PHP Version

8.3

### Laravel Version

11

### Notes

None

**Comment by stephenjude** [comment]
@HeartlandTechie can you make a PR for this?

**Comment by stephenjude** [comment]
I can't find the need for this update. 

$panel->plugin() works just like $panel->plugins([]) but accepts only one parameter;

**Comment by chrillep** [comment]
its the root backslash that is missing.

```diff
- Stephenjude\FilamentFeatureFlag\FeatureFlagPlugin::make()
+ \Stephenjude\FilamentFeatureFlag\FeatureFlagPlugin::make()
```

but array is preferred.

```php
->plugins([
    \Stephenjude\FilamentFeatureFlag\FeatureFlagPlugin::make()
]);
```
