### ISSUE TITLE
[Bug]: Why do you need to downgrade this dependency on newer version?

### ISSUE THREAD

**Issue by galihlprakoso** [stephenjude/filament-feature-flags#13]
### What happened?

I cannot used it on my Laravel 11 project.

### How to reproduce the bug

Just try to upgrade to 2.0.1 using Laravel 11.

### Package Version

2.0.1

### PHP Version

8.3

### Laravel Version

11.0.0

### Notes

https://github.com/stephenjude/filament-feature-flags/blob/219a8f0e2f4d189d5cf22f715337139ddafbb9a7/composer.json#L23

Why do you need to downgrade this? illuminate/contracts I can't use it with my Laravel 11.

**Comment by stephenjude** [comment]
@galihlprakoso I just tagged a release that fixed this.

I think the L11 support added by @simonhamp got lost in merge conflicts.

**Comment by galihlprakoso** [comment]
> @galihlprakoso I just tagged a release that fixed this.
> 
> I think the L11 support added by @simonhamp got lost in merge conflicts.

Thank you so much! I've just forked the repository.. I'll try to update to latest version! Thanks! @stephenjude
