### ISSUE TITLE
[Bug]: Not compatible with illuminate/contracts:^11

### ISSUE THREAD

**Issue by liamfirth** [stephenjude/filament-feature-flags#7]
### What happened?

Cannot currently install this using composer and the newest version of Laravel Sanctum (might be other packages as well) which pulls in illuminate/contracts tagged with the latest version ^11. Is it possible to update this to support the latest illuminate/contracts package version - e.g. Filament 3 has "   "illuminate/contracts": "^10.45|^11.0". 

### How to reproduce the bug

`composer require laravel/framework laravel/sanctum filament/filament stephenjude/filament-feature-flags`

```
  Problem 1
    - Only one of these can be installed: illuminate/contracts[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.12, v11.0.0, ..., v11.9.2], laravel/framework[v11.9.0, v11.9.1, v11.9.2]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - stephenjude/filament-feature-flags[1.0.0, ..., 1.0.8] require illuminate/contracts ^10.0 -> satisfiable by illuminate/contracts[v10.0.0, ..., v10.48.12].
    - Root composer.json requires stephenjude/filament-feature-flags ^1.0 -> satisfiable by stephenjude/filament-feature-flags[1.0.0, ..., 1.0.8].
    - Root composer.json requires laravel/framework ^11.9 -> satisfiable by laravel/framework[v11.9.0, v11.9.1, v11.9.2].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/framework:*" to figure out if any version is installable, or "composer require laravel/framework:^2.1" if you know which you need.
```

### Package Version

1.0.8

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by stephenjude** [comment]
@liamfirth this not a bug, the package currently does not support Laravel 11, you can submit a PR for this.
